### PR TITLE
TYPO3 v12

### PR DESCRIPTION
**Pull request by vnc-omol**
Hi, thank you for your great extension which we use since years!
I made some changes to make it typo3 12 compatible. This works for our needs... 
You might want to give it a try ;-)

### CODE REVIEW

**Comment by jloderhose** [comment]
Please merge this PR and publish a new release of the extension. It works like a charm with TYPO3 12 (in composer mode). powermailpdf is a valuable add on to powermail. It would be great to see the official support continued.

Thanks @vnc-omol for providing TYPO3 12 compatibility!

**Comment by Starkmann** [comment]
> Hi, thank you for your great extension which we use since years! I made some changes to make it typo3 12 compatible. Can you please explain the purpose oft this code. It seems to be related to the checkbox feature. https://github.com/undkonsorten/powermailpdf/issues/21

**Comment by Starkmann** [comment]
@vnc-omol Can you please explain the purpose oft this code. It seems to be related to the checkbox feature. https://github.com/undkonsorten/powermailpdf/issues/21

**Comment by vnc-omol** [comment]
> @vnc-omol Can you please explain the purpose oft this code. It seems to be related to the checkbox feature. #21

@Starkmann I think, I just migrated the signal slot dispatcher from Classes/Pdf.php to an eventlistener

**Pull request merged**
